apiVersion: v1
kind: Service
metadata:
  name: pubsub
  labels:
    app: pubsub
spec:
  ports:
  - port: 6379
  type: ClusterIP
  selector:
    app: pubsub
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pubsub
spec:
  selector:
    matchLabels:
      app: pubsub 
  serviceName: pubsub
  replicas: 3
  template:
    metadata:
      labels:
        app: pubsub 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pubsub
        image: redis
        ports:
        - containerPort: 6379
  