apiVersion: v1
kind: Service
metadata:
  name: pubsub-service
  labels:
    app: pubsub-app
spec:
  ports:
  - port: 6379
  type: ClusterIP
  selector:
    app: pubsub-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pubsub-stateful-set
spec:
  selector:
    matchLabels:
      app: pubsub-app
  serviceName: pubsub-service
  replicas: 2
  template:
    metadata:
      labels:
        app: pubsub-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pubsub-container
          image: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 256Mi
              cpu: 200m
  